# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
# source: query.sql
import dataclasses
from typing import Iterator, Optional

import sqlalchemy

from querytest import models


DELETE_BAR_BY_ID_AND_NAME = """-- name: delete_bar_by_id_and_name \\:execrows
DELETE FROM bar WHERE id = :p1 AND name = :p2
"""


@dataclasses.dataclass()
class DeleteBarByIDAndNameParamsDTO:
    id: int
    name: str


GET_BAR = """-- name: get_bar \\:one
SELECT id, name FROM bar WHERE id = :p1 LIMIT 1
"""


LIST_BAR_UPPER_NAMES = """-- name: list_bar_upper_names \\:many
SELECT id, name AS upper_name FROM bar ORDER BY id
"""


@dataclasses.dataclass()
class ListBarUpperNamesRowDTO:
    id: int
    upper_name: str


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def delete_bar_by_id_and_name(self, arg: DeleteBarByIDAndNameParamsDTO) -> int:
        result = self._conn.execute(sqlalchemy.text(DELETE_BAR_BY_ID_AND_NAME), {"p1": arg.id, "p2": arg.name})
        return result.rowcount

    def get_bar(self, *, id: int) -> Optional[models.BarDTO]:
        row = self._conn.execute(sqlalchemy.text(GET_BAR), {"p1": id}).first()
        if row is None:
            return None
        return models.BarDTO(
            id=row[0],
            name=row[1],
        )

    def list_bar_upper_names(self) -> Iterator[ListBarUpperNamesRowDTO]:
        result = self._conn.execute(sqlalchemy.text(LIST_BAR_UPPER_NAMES))
        for row in result:
            yield ListBarUpperNamesRowDTO(
                id=row[0],
                upper_name=row[1],
            )
